// routes/export.js
// Generates a complete downloadable Vite + React project from a System.
// Every page with generatedCode becomes a real component.
// Theme tokens become CSS variables.
// React Router connects all pages with a sidebar.

import express from 'express'
import JSZip from 'jszip'
import System from '../models/System.js'
import Page from '../models/Page.js'
import Theme from '../models/Theme.js'
import { protect } from '../middleware/auth.js'
import { errorResponse } from '../utils/helpers.js'

const router = express.Router()

// ── GET /api/export/:slug — Download System as zip ────────────────────────
router.get('/:slug', protect, async (req, res, next) => {
  try {
    const system = await System.findOne({ slug: req.params.slug, ownerId: req.user._id })
    if (!system) return errorResponse(res, 'System not found', 404)

    const [pages, theme] = await Promise.all([
      Page.find({ systemId: system._id }).sort({ order: 1 }),
      Theme.findOne({ systemId: system._id }),
    ])

    const tokens = theme?.tokens || {}
    const zip = new JSZip()

    // ── index.html ─────────────────────────────────────────────────────────
    zip.file('index.html', `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${system.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`)

    // ── package.json ───────────────────────────────────────────────────────
    zip.file('package.json', JSON.stringify({
      name: system.slug,
      version: '1.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        'react-router-dom': '^6.22.0',
      },
      devDependencies: {
        '@vitejs/plugin-react': '^4.2.1',
        vite: '^5.0.0',
      },
    }, null, 2))

    // ── vite.config.js ─────────────────────────────────────────────────────
    zip.file('vite.config.js', `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`)

    // ── src/main.jsx ───────────────────────────────────────────────────────
    zip.file('src/main.jsx', `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './theme.css'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>
)`)

    // ── src/theme.css ──────────────────────────────────────────────────────
    zip.file('src/theme.css', `/* ${system.name} — Theme */
/* Generated by Krimson */

:root {
  --bg: ${tokens.backgroundColor || '#09090B'};
  --surface: ${tokens.surfaceColor || '#111113'};
  --border: ${tokens.borderColor || '#27272A'};
  --accent: ${tokens.accentColor || '#DC2626'};
  --text-primary: ${tokens.primaryTextColor || '#FAFAFA'};
  --text-secondary: ${tokens.secondaryTextColor || '#A1A1AA'};
  --font: ${tokens.fontFamily || 'Inter'}, system-ui, sans-serif;
  --radius: ${tokens.borderRadius === 'none' ? '0' : tokens.borderRadius === 'subtle' ? '4px' : tokens.borderRadius === 'rounded' ? '12px' : '8px'};
}

* { box-sizing: border-box; margin: 0; padding: 0; }

html, body {
  background-color: var(--bg);
  color: var(--text-primary);
  font-family: var(--font);
  font-size: 14px;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}

a { color: inherit; text-decoration: none; }
`)

    // ── src/App.jsx ────────────────────────────────────────────────────────
    const codedPages = pages.filter(p => p.generatedCode)
    const allPages = pages

    // Build sidebar nav items — use all pages, coded ones are navigable
    const navItems = allPages.map(p => ({
      name: p.name,
      slug: p.slug,
      hascode: !!p.generatedCode,
    }))

    const imports = codedPages.map(p =>
      `import ${toPascalCase(p.slug)} from './pages/${toPascalCase(p.slug)}.jsx'`
    ).join('\n')

    const routes = codedPages.map(p =>
      `          <Route path="/${p.slug}" element={<${toPascalCase(p.slug)} />} />`
    ).join('\n')

    const firstRoute = codedPages.length > 0
      ? `<Route index element={<Navigate to="/${codedPages[0].slug}" replace />} />`
      : `<Route index element={<div style={{padding:'2rem',color:'var(--text-secondary)'}}>No pages generated yet.</div>} />`

    zip.file('src/App.jsx', `import { BrowserRouter, Routes, Route, NavLink, Navigate } from 'react-router-dom'
${imports}

const navItems = ${JSON.stringify(navItems, null, 2)}

const Sidebar = () => (
  <aside style={{
    width: '200px',
    flexShrink: 0,
    borderRight: '1px solid var(--border)',
    backgroundColor: 'var(--bg)',
    display: 'flex',
    flexDirection: 'column',
    padding: '16px 12px',
    position: 'fixed',
    top: 0,
    left: 0,
    bottom: 0,
  }}>
    <div style={{ marginBottom: '24px', padding: '0 12px' }}>
      <h1 style={{ fontSize: '14px', fontWeight: 700, color: 'var(--text-primary)' }}>
        ${system.name}
      </h1>
      <p style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '2px' }}>
        ${system.category || ''}
      </p>
    </div>
    <nav style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
      {navItems.map(item => item.hascode ? (
        <NavLink
          key={item.slug}
          to={\`/\${item.slug}\`}
          style={({ isActive }) => ({
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            padding: '8px 12px',
            borderRadius: '6px',
            fontSize: '13px',
            fontWeight: 500,
            color: isActive ? 'var(--text-primary)' : 'var(--text-secondary)',
            backgroundColor: isActive ? 'var(--surface)' : 'transparent',
            textDecoration: 'none',
          })}
        >
          <span style={{
            width: '6px', height: '6px', borderRadius: '50%',
            backgroundColor: 'var(--accent)', flexShrink: 0,
          }} />
          {item.name}
        </NavLink>
      ) : (
        <div key={item.slug} style={{
          display: 'flex', alignItems: 'center', gap: '8px',
          padding: '8px 12px', borderRadius: '6px',
          fontSize: '13px', color: '#3F3F46',
        }}>
          <span style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: '#3F3F46', flexShrink: 0 }} />
          {item.name}
        </div>
      ))}
    </nav>
  </aside>
)

export default function App() {
  return (
    <BrowserRouter>
      <div style={{ display: 'flex', minHeight: '100vh' }}>
        <Sidebar />
        <main style={{ flex: 1, marginLeft: '200px', minHeight: '100vh' }}>
          <Routes>
            ${firstRoute}
${routes}
          </Routes>
        </main>
      </div>
    </BrowserRouter>
  )
}`)

    // ── src/pages/*.jsx ────────────────────────────────────────────────────
    for (const page of codedPages) {
      const componentName = toPascalCase(page.slug)
      let code = page.generatedCode

      // Strip any existing export/import statements the AI may have added
      code = code
        .replace(/^import\s+.*$/gm, '')
        .replace(/export\s+default\s+function\s+GeneratedPage/g, `function ${componentName}`)
        .replace(/export\s+default\s+function\s+${componentName}/g, `function ${componentName}`)
        .replace(/export\s+default\s+GeneratedPage\s*;?/g, '')
        .replace(/export\s+default\s+${componentName}\s*;?/g, '')
        .replace(/function\s+GeneratedPage\b/g, `function ${componentName}`)
        // Fix React.useState/useEffect → useState/useEffect (since we import them directly)
        .replace(/React\.useState/g, 'useState')
        .replace(/React\.useEffect/g, 'useEffect')
        .replace(/React\.useRef/g, 'useRef')
        .trim()

      // Wrap with guaranteed correct header and footer
      const wrapped = `import { useState, useEffect, useRef } from 'react'

${code}

export default ${componentName}
`
      zip.file(`src/pages/${componentName}.jsx`, wrapped)
    }

    // ── README.md ──────────────────────────────────────────────────────────
    zip.file('README.md', `# ${system.name}

${system.description || ''}

Generated by [Krimson](https://krimson-frontend.vercel.app) — System-first UI builder.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:5173

## Pages

${allPages.map(p => `- **${p.name}** (/${p.slug})${p.generatedCode ? '' : ' — no code generated yet'}`).join('\n')}

## Theme

| Token | Value |
|-------|-------|
| Background | ${tokens.backgroundColor || '#09090B'} |
| Surface | ${tokens.surfaceColor || '#111113'} |
| Accent | ${tokens.accentColor || '#DC2626'} |
| Font | ${tokens.fontFamily || 'Inter'} |
`)

    // ── Generate and send zip ──────────────────────────────────────────────
    const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })

    const filename = `${system.slug}-krimson.zip`
    res.set({
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': buffer.length,
    })
    res.send(buffer)

  } catch (error) {
    next(error)
  }
})

// Convert slug to PascalCase component name
// dashboard → Dashboard, user-profile → UserProfile
function toPascalCase(slug) {
  return slug
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

export default router